import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  weight: ["400", "700"], // ✅ 700 = bold, 400 = regular
  subsets: ["thai"], // ✅ รองรับภาษาไทย
  variable: "--font-kanit", // ✅ ตั้งชื่อ CSS variable
  display: "swap", // (แนะนำเพื่อให้โหลดเร็ว)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className}`}
      >
        <nav className="bg-zinc-100 h-10 text-white p-2 text-lg"><p>Banfarmknum</p></nav>
        <div className="mt-10 px-50 font-bold">
          {children}
        </div>

      </body>
    </html>
  );
}
