import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["thai"],
  weight: ["400", "500", "700"], // เลือกน้ำหนักที่ใช้
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} font-sans antialiased`}
      >
        <nav className="bg-green-700 h-10 text-white p-2 text-lg"><p>บ้านฟาร์มขนม</p></nav>
        {children}
      </body>
    </html>
  );
}
